CREATE TYPE user_role AS ENUM (
  'GUEST',
  'REGISTERED_USER',
  'VENDOR',
  'MANAGER',
  'VEHICLE_OWNER',
  'SUPPORT_STAFF'
);

CREATE TYPE booking_status AS ENUM (
  'PENDING',
  'CONFIRMED',
  'IN_TRANSIT',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE payment_status AS ENUM (
  'PENDING',
  'COMPLETED',
  'FAILED',
  'REFUNDED'
);

CREATE TYPE notification_type AS ENUM (
  'BOOKING_CONFIRMATION',
  'STATUS_UPDATE',
  'PAYMENT_CONFIRMATION',
  'CANCELLATION',
  'REMINDER'
);